//! The PTY thread of a pane: reads the program's output into the terminal
//! and writes input and replies back. nuntio runs its own loop instead of
//! alacritty's so it sees the output stream before the parser does.

use std::borrow::Cow;
use std::collections::VecDeque;
use std::io::{self, ErrorKind};
use std::num::NonZeroUsize;
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex, MutexGuard, PoisonError, mpsc};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use alacritty_terminal::event::{Event, EventListener, WindowSize};
use alacritty_terminal::sync::FairMutex;
use alacritty_terminal::term::{Term, TermMode};
#[cfg(windows)]
use alacritty_terminal::tty;
use alacritty_terminal::vte::ansi::Processor;
use polling::{Events, PollMode, Poller};

use crate::backend::{Backend, BackendEvent};
use crate::image::{self, CellGeometry, ImageKey, ImageStore, TermImage};
use crate::image_scan::{ImageRequest, ImageScanner, ScanEvent};
use crate::osc_cwd::{CwdScanner, ReportedDir};
use crate::pane::Listener;

/// Size of the read buffer.
const READ_BUFFER_SIZE: usize = 0x10_0000;
/// Bytes parsed per read pass before the term lock is given up again, so
/// the main thread can draw during floods of output.
const MAX_LOCKED_READ: usize = u16::MAX as usize;
/// How long the PTY thread waits for messages between checks whether an
/// image is decoded.
const DECODE_POLL: Duration = Duration::from_millis(5);
/// The escape that begins a synchronized update (DEC 2026).
const BSU: &[u8] = b"\x1b[?2026h";
/// Read passes after the program exited: 2 MiB, more than WslPipe buffers
/// (`MAX_BUFFERED` + one read), but bounded for processes that outlive it
/// and keep writing.
const EXIT_DRAIN_PASSES: usize = 32;

/// A message to the PTY thread.
pub(crate) enum Msg {
    /// Bytes for the program: typed or pasted input.
    Input(Cow<'static, [u8]>),
    /// Bytes the terminal generated for the program (answers to queries);
    /// counted by the [`ReplyBudget`] and dropped while the program doesn't
    /// read them.
    Reply(Vec<u8>),
    Resize(WindowSize),
    Shutdown,
    /// An image decode finished; only `decode_serving` waits for it, the
    /// loop ignores it.
    Decoded,
}

/// Most bytes of terminal-generated replies waiting for a program that doesn't read them.
pub(crate) const MAX_PENDING_REPLY_BYTES: usize = 64 * 1024;

/// Bytes of terminal-generated replies that were sent to the PTY thread and
/// not yet written (or dropped).
#[derive(Default)]
pub(crate) struct ReplyBudget {
    pending: AtomicUsize,
    logged: AtomicBool,
}

impl ReplyBudget {
    /// Reserve `len` bytes; false if that would exceed the cap (the reply
    /// is dropped). Logs once at debug.
    pub(crate) fn try_reserve(&self, len: usize) -> bool {
        let mut pending = self.pending.load(Ordering::Acquire);
        let reserved = loop {
            let Some(total) = pending
                .checked_add(len)
                .filter(|total| *total <= MAX_PENDING_REPLY_BYTES)
            else {
                break false;
            };
            match self.pending.compare_exchange_weak(
                pending,
                total,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => break true,
                Err(now) => pending = now,
            }
        };
        if !reserved && !self.logged.swap(true, Ordering::Relaxed) {
            tracing::debug!("dropping replies: the program doesn't read its input");
        }
        reserved
    }

    pub(crate) fn release(&self, len: usize) {
        self.pending.fetch_sub(len, Ordering::AcqRel);
    }

    #[cfg(test)]
    fn pending(&self) -> usize {
        self.pending.load(Ordering::Acquire)
    }
}

/// Bytes waiting to be written to the PTY.
pub(crate) struct Queued {
    bytes: Cow<'static, [u8]>,
    /// Generated by the terminal: counted by the [`ReplyBudget`] and
    /// dropped when the program doesn't read.
    reply: bool,
}

/// Apply a message to the loop's state.
fn handle_msg(
    msg: Msg,
    write_list: &mut VecDeque<Queued>,
    resize: &mut Option<WindowSize>,
    shutdown: &mut bool,
) {
    match msg {
        // An empty write would keep the PTY registered as writable.
        Msg::Input(bytes) if bytes.is_empty() => {}
        Msg::Input(bytes) => write_list.push_back(Queued {
            bytes,
            reply: false,
        }),
        Msg::Reply(bytes) if bytes.is_empty() => {}
        Msg::Reply(bytes) => write_list.push_back(Queued {
            bytes: Cow::Owned(bytes),
            reply: true,
        }),
        Msg::Resize(size) => *resize = Some(size),
        Msg::Shutdown => *shutdown = true,
        Msg::Decoded => {}
    }
}

/// Closes the pane through the usual Exit flow when the PTY thread ends
/// without a Shutdown (errors, panics).
struct ExitGuard {
    term: Arc<FairMutex<Term<Listener>>>,
    listener: Listener,
    armed: bool,
}

impl ExitGuard {
    fn new(term: Arc<FairMutex<Term<Listener>>>, listener: Listener) -> Self {
        Self {
            term,
            listener,
            armed: true,
        }
    }

    fn disarm(&mut self) {
        self.armed = false;
    }

    /// Send Exit and Wakeup, once.
    fn exit(&mut self) {
        if std::mem::replace(&mut self.armed, false) {
            self.term.lock().exit();
            self.listener.send_event(Event::Wakeup);
        }
    }
}

impl Drop for ExitGuard {
    fn drop(&mut self) {
        self.exit();
    }
}

/// Sends [`Msg`]s to the PTY thread and wakes it up.
#[derive(Clone)]
pub(crate) struct LoopSender {
    tx: mpsc::Sender<Msg>,
    poller: Arc<Poller>,
}

impl LoopSender {
    /// Send `msg`; does nothing once the thread is gone.
    pub(crate) fn send(&self, msg: Msg) {
        if self.tx.send(msg).is_ok() {
            let _ = self.poller.notify();
        }
    }
}

pub(crate) struct IoLoop {
    poll: Arc<Poller>,
    /// The pid of the process behind `pty`, shared with the pane; 0 if unknown.
    child_pid: Arc<AtomicU32>,
    /// For a WSL pane: the same shell through ConPTY, if nuntio-wsl fails.
    #[cfg(windows)]
    fallback: Option<tty::Options>,
    rx: mpsc::Receiver<Msg>,
    tx: mpsc::Sender<Msg>,
    term: Arc<FairMutex<Term<Listener>>>,
    listener: Listener,
    parser: Processor,
    cwd: CwdScanner,
    reported_dir: Arc<Mutex<Option<ReportedDir>>>,
    scanner: ImageScanner,
    images: Arc<Mutex<ImageStore>>,
    /// Input waiting for the PTY to become writable.
    write_list: VecDeque<Queued>,
    /// Bytes of the front of `write_list` already written.
    written: usize,
    /// A [`Msg::Shutdown`] arrived while an image was decoding.
    shutdown_requested: bool,
    /// The slave side hung up: reading is over, only the exit is awaited.
    hung_up: bool,
    /// The latest resize not yet applied to the PTY.
    resize: Option<WindowSize>,
    /// Last: dropping the PTY may block until the child exits, so the grid
    /// and images are freed first.
    pty: Backend,
}

impl IoLoop {
    pub(crate) fn new(
        pty: Backend,
        #[cfg(windows)] fallback: Option<tty::Options>,
        term: Arc<FairMutex<Term<Listener>>>,
        listener: Listener,
        reported_dir: Arc<Mutex<Option<ReportedDir>>>,
        images: Arc<Mutex<ImageStore>>,
    ) -> io::Result<Self> {
        let (tx, rx) = mpsc::channel();
        let child_pid = Arc::new(AtomicU32::new(pty.pid().unwrap_or(0)));
        Ok(Self {
            poll: Arc::new(Poller::new()?),
            child_pid,
            #[cfg(windows)]
            fallback,
            rx,
            tx,
            term,
            listener,
            parser: Processor::new(),
            cwd: CwdScanner::default(),
            reported_dir,
            scanner: ImageScanner::default(),
            images,
            write_list: VecDeque::new(),
            written: 0,
            shutdown_requested: false,
            hung_up: false,
            resize: None,
            pty,
        })
    }

    pub(crate) fn sender(&self) -> LoopSender {
        LoopSender {
            tx: self.tx.clone(),
            poller: self.poll.clone(),
        }
    }

    /// The pid of the process behind the pane, which changes when a WSL
    /// pane falls back to ConPTY; 0 if unknown.
    pub(crate) fn child_pid(&self) -> Arc<AtomicU32> {
        self.child_pid.clone()
    }

    pub(crate) fn spawn(self) -> JoinHandle<()> {
        alacritty_terminal::thread::spawn_named("PTY reader", move || self.run())
    }

    fn run(mut self) {
        let mut exit = ExitGuard::new(self.term.clone(), self.listener.clone());
        let mut buf = vec![0u8; READ_BUFFER_SIZE];
        let poll = self.poll.clone();
        let mut interest = polling::Event::readable(0);
        // SAFETY: the PTY lives in `self` as long as its registration; it is
        // deregistered before the loop returns.
        if let Err(err) = unsafe { self.pty.register(&poll, interest, PollMode::Level) } {
            tracing::error!(%err, "registering the PTY failed");
            return;
        }
        let mut events = Events::with_capacity(NonZeroUsize::new(1024).expect("non-zero"));
        // A read pass that stopped at `MAX_LOCKED_READ` may have left output
        // behind. On Windows no further event announces it (alacritty's pipe
        // reader only wakes the poller once it was found empty), so the next
        // pass reads without waiting.
        let mut more_output = false;
        // The hung-up PTY is out of the poller's interest.
        let mut parked = false;

        loop {
            // Wake up when a synchronized update (DEC 2026) times out.
            let timeout = if more_output || self.resize.is_some() {
                Some(Duration::ZERO)
            } else {
                self.parser
                    .sync_timeout()
                    .sync_timeout()
                    .map(|t| t.saturating_duration_since(Instant::now()))
            };
            events.clear();
            if let Err(err) = poll.wait(&mut events, timeout) {
                if err.kind() == ErrorKind::Interrupted {
                    continue;
                }
                tracing::error!(%err, "polling the PTY failed");
                break;
            }

            let mut received = false;
            while !self.shutdown_requested
                && let Ok(msg) = self.rx.try_recv()
            {
                received = true;
                handle_msg(
                    msg,
                    &mut self.write_list,
                    &mut self.resize,
                    &mut self.shutdown_requested,
                );
            }
            if self.shutdown_requested {
                exit.disarm();
                break;
            }

            if events.is_empty() && !received && !more_output && self.resize.is_none() {
                // Flush a synchronized update only at its deadline: messages
                // taken while an image decoded can end the wait early.
                if self
                    .parser
                    .sync_timeout()
                    .sync_timeout()
                    .is_some_and(|t| t <= Instant::now())
                {
                    self.parser.stop_sync(&mut *self.term.lock());
                    self.listener.send_event(Event::Wakeup);
                }
                continue;
            }

            // alacritty's event keys are private; the child event check
            // doesn't block, so it runs on every pass. A hang-up counts as
            // readable: the read drains what is left and ends with EIO or 0,
            // which parks the PTY (see `hung_up`).
            let (mut readable, mut writable) = (more_output, false);
            for event in events.iter() {
                readable |= event.readable;
                writable |= event.writable && !event.is_interrupt();
            }

            match self.pty.next_event() {
                Some(BackendEvent::Exited(status)) => {
                    if let Some(status) = status {
                        self.listener.send_event(Event::ChildExit(status));
                    }
                    self.drain_after_exit(&mut buf);
                    exit.exit();
                    self.child_pid.store(0, Ordering::Relaxed);
                    break;
                }
                #[cfg(windows)]
                Some(BackendEvent::HelperFailed(status)) => {
                    self.drain_after_exit(&mut buf);
                    tracing::warn!(?status, "nuntio-wsl did not start, falling back to ConPTY");
                    if self.fall_back(&poll, interest) {
                        more_output = false;
                        continue;
                    }
                    exit.exit();
                    break;
                }
                None => {}
            }

            // Not before the exit check: no resize may reach an exited
            // ConPTY, whose `on_resize` asserts.
            if let Some(size) = self.resize.take() {
                self.pty.resize(size);
            }

            more_output = false;
            if readable && !self.hung_up {
                let result = self.pty_read(&mut buf);
                if self.shutdown_requested {
                    exit.disarm();
                    break;
                }
                match result {
                    Ok(capped) => more_output = capped,
                    Err(err) => {
                        tracing::error!(%err, "reading from the PTY failed");
                        break;
                    }
                }
            }

            if self.hung_up {
                if !parked {
                    // epoll reports a hung-up master forever; only SIGCHLD and
                    // notify() wake the loop now.
                    if let Err(err) =
                        self.pty
                            .reregister(&poll, polling::Event::none(0), PollMode::Oneshot)
                    {
                        tracing::error!(%err, "parking the PTY failed");
                        break;
                    }
                    parked = true;
                }
                continue;
            }

            if writable && let Err(err) = self.pty_write() {
                tracing::error!(%err, "writing to the PTY failed");
                break;
            }

            let needs_write = !self.write_list.is_empty();
            if needs_write != interest.writable {
                interest.writable = needs_write;
                if let Err(err) = self.pty.reregister(&poll, interest, PollMode::Level) {
                    tracing::error!(%err, "re-registering the PTY failed");
                    break;
                }
            }
        }

        let _ = self.pty.deregister(&poll);
        self.child_pid.store(0, Ordering::Relaxed);
    }

    /// Read the output left after the program exited, but not forever: a
    /// process it started may keep the PTY open and write on.
    fn drain_after_exit(&mut self, buf: &mut [u8]) {
        for _ in 0..EXIT_DRAIN_PASSES {
            if !matches!(self.pty_read(buf), Ok(true)) || self.shutdown_requested {
                break;
            }
        }
    }

    /// Read and parse the available output, holding the term lock for at
    /// most [`MAX_LOCKED_READ`] bytes. Inline images and cell size queries
    /// are taken out of the stream and handled here, in stream order.
    /// Returns whether the pass stopped at the limit with output possibly left.
    fn pty_read(&mut self, buf: &mut [u8]) -> io::Result<bool> {
        let term = self.term.clone();
        // Reserve the next term lock for the PTY thread.
        let mut lease = Some(term.lease());
        let mut guard = None;
        let mut processed = 0;
        let mut capped = false;
        // Output reached the grid, even if a synchronized update is open now.
        let mut applied = false;
        // Text was parsed outside a synchronized update.
        let mut outside_text = false;
        loop {
            let limit = read_limit(buf.len());
            let n = match self.pty.read(&mut buf[..limit]) {
                Ok(0) => {
                    // On macOS the master reads 0 once the slave hung up.
                    #[cfg(unix)]
                    if matches!(self.pty, Backend::Pty(_)) {
                        self.hung_up = true;
                    }
                    break;
                }
                Ok(n) => n,
                Err(err)
                    if matches!(err.kind(), ErrorKind::WouldBlock | ErrorKind::Interrupted) =>
                {
                    break;
                }
                // On Linux, reading the master fails with EIO once the slave
                // hung up. That is the end of the data, so output read
                // earlier in this pass still gets its final wakeup.
                Err(err) if is_eio(&err) => {
                    self.hung_up = true;
                    break;
                }
                Err(err) => return Err(err),
            };
            if let Some(dir) = self.cwd.feed(&buf[..n]) {
                *lock(&self.reported_dir) = Some(dir);
            }
            let parser = &mut self.parser;
            let listener = &self.listener;
            let images = &self.images;
            let mut input = PtyInput {
                pty: &mut self.pty,
                rx: &self.rx,
                tx: &self.tx,
                write_list: &mut self.write_list,
                written: &mut self.written,
                resize: &mut self.resize,
                budget: listener.reply_budget(),
                shutdown_requested: &mut self.shutdown_requested,
            };
            self.scanner.feed(&buf[..n], &mut |event| match event {
                ScanEvent::Text(bytes) => {
                    let term = &mut **guard.get_or_insert_with(|| term.lock_unfair());
                    let was_sync = parser.sync_timeout().sync_timeout().is_some();
                    let before = parser.sync_bytes_count();
                    parser.advance(term, bytes);
                    let syncing = parser.sync_timeout().sync_timeout().is_some();
                    // Output reached the grid although an update is open now:
                    // a frame ended (even if the next one began), or text came
                    // before a BSU. The scanner splits escapes, so a lone ESC
                    // or the first part of a BSU isn't text.
                    if was_sync {
                        applied |= parser.sync_bytes_count() < before + bytes.len();
                    } else if !syncing && !BSU.starts_with(bytes) {
                        outside_text = true;
                    }
                }
                ScanEvent::CellSizeQuery => {
                    let term = &mut **guard.get_or_insert_with(|| term.lock_unfair());
                    with_flushed_sync(parser, term, |_| {
                        let size = listener.window_size();
                        listener.reply(format!("\x1b[6;{};{}t", size.cell_height, size.cell_width));
                    });
                }
                ScanEvent::Image(request) => {
                    if *input.shutdown_requested {
                        return;
                    }
                    let args = image::parse_args(&request.args);
                    if !args.inline {
                        tracing::debug!("inline image without inline=1 ignored");
                        return;
                    }
                    let geometry = CellGeometry::from(listener.window_size());
                    // Hashing the payload and decoding take a while: let the
                    // main thread draw meanwhile.
                    drop(guard.take());
                    drop(lease.take());
                    // Keystrokes and replies must not wait for a stream of
                    // images, not even cached ones.
                    service(&mut input);
                    if *input.shutdown_requested {
                        return;
                    }
                    let key = ImageKey::new(&request, geometry);
                    let cached = {
                        let store = lock(images);
                        store
                            .cached(key)
                            .and_then(|id| Some((id, store.get(id)?.clone())))
                    };
                    let (id, image, inserted) = match cached {
                        Some((id, image)) => {
                            lease = Some(term.lease());
                            (id, image, false)
                        }
                        None => {
                            let decoded = decode_serving(&mut input, &request, &args, geometry);
                            if *input.shutdown_requested {
                                return;
                            }
                            lease = Some(term.lease());
                            let Some(decoded) = decoded else {
                                return;
                            };
                            let mut store = lock(images);
                            let id = store.insert(key, decoded);
                            let image = store.get(id).expect("just inserted").clone();
                            (id, image, true)
                        }
                    };
                    let term = &mut **guard.get_or_insert_with(|| term.lock_unfair());
                    // The screen is known only once the output buffered in a
                    // synchronized update is applied.
                    let mut alt = false;
                    with_flushed_sync(parser, term, |term| {
                        image::place(term, id, &image);
                        alt = term.mode().contains(TermMode::ALT_SCREEN);
                    });
                    let mut store = lock(images);
                    store.placed(id, alt);
                    // Memory only grows with new images; cache hits don't
                    // need to scan the grid.
                    if inserted {
                        store.evict(term);
                    }
                }
            });
            if self.shutdown_requested {
                break;
            }
            processed += n;
            if processed >= MAX_LOCKED_READ {
                capped = true;
                break;
            }
        }
        drop(guard);
        drop(lease);
        // Redraw, but not in the middle of a synchronized update unless a
        // frame or text before it was applied: its end, or its timeout in
        // `run`, wakes the main thread.
        if processed > 0
            && (applied || outside_text || self.parser.sync_timeout().sync_timeout().is_none())
        {
            self.listener.send_event(Event::Wakeup);
        }
        Ok(capped)
    }

    /// Write queued input until the PTY would block.
    fn pty_write(&mut self) -> io::Result<()> {
        write_pending(
            &mut self.pty,
            &mut self.write_list,
            &mut self.written,
            self.listener.reply_budget(),
        )
    }

    /// Replace a failed nuntio-wsl with the same shell through ConPTY.
    /// Returns false if there is no fallback or it didn't start either.
    #[cfg(windows)]
    fn fall_back(&mut self, poll: &Arc<Poller>, interest: polling::Event) -> bool {
        let _ = self.pty.deregister(poll);
        let Some(options) = self.fallback.take() else {
            return false;
        };
        let pty = match tty::new(&options, self.listener.window_size(), 0) {
            Ok(pty) => pty,
            Err(err) => {
                tracing::error!(%err, "starting the ConPTY fallback failed");
                return false;
            }
        };
        self.pty = Backend::Pty(pty);
        // SAFETY: as for the first registration in `run`.
        if let Err(err) = unsafe { self.pty.register(poll, interest, PollMode::Level) } {
            tracing::error!(%err, "registering the ConPTY fallback failed");
            return false;
        }
        self.child_pid
            .store(self.pty.pid().unwrap_or(0), Ordering::Relaxed);
        // Not written into the grid: ConPTY may clear the screen at startup.
        self.listener.helper_failed();
        true
    }
}

/// The parts of the loop that keep working while an image decodes.
struct PtyInput<'a> {
    pty: &'a mut Backend,
    rx: &'a mpsc::Receiver<Msg>,
    tx: &'a mpsc::Sender<Msg>,
    write_list: &'a mut VecDeque<Queued>,
    written: &'a mut usize,
    resize: &'a mut Option<WindowSize>,
    budget: &'a ReplyBudget,
    shutdown_requested: &'a mut bool,
}

/// Take pending messages and write what the PTY accepts, without blocking,
/// between inline images.
fn service(input: &mut PtyInput<'_>) {
    while !*input.shutdown_requested
        && let Ok(msg) = input.rx.try_recv()
    {
        handle_msg(
            msg,
            input.write_list,
            input.resize,
            input.shutdown_requested,
        );
    }
    // A failure shows again when the loop writes next.
    let _ = write_pending(input.pty, input.write_list, input.written, input.budget);
}

/// Reading the master fails with EIO once the slave hung up (Linux).
fn is_eio(err: &io::Error) -> bool {
    #[cfg(target_os = "linux")]
    {
        err.raw_os_error() == Some(libc::EIO)
    }
    #[cfg(not(target_os = "linux"))]
    {
        let _ = err;
        false
    }
}

/// How much of a `buf_len` buffer one read may fill.
fn read_limit(buf_len: usize) -> usize {
    MAX_LOCKED_READ.min(buf_len)
}

/// Write the queued input to the PTY until it would block. Replies are
/// dropped, not written, while the PTY already holds too many unread bytes.
fn write_pending(
    pty: &mut Backend,
    write_list: &mut VecDeque<Queued>,
    written: &mut usize,
    budget: &ReplyBudget,
) -> io::Result<()> {
    while let Some(front) = write_list.front() {
        let len = front.bytes.len();
        if front.reply && *written == 0 && pty.queued_bytes() >= MAX_PENDING_REPLY_BYTES {
            write_list.pop_front();
            budget.release(len);
            continue;
        }
        match pty.write(&front.bytes[*written..]) {
            Ok(0) => break,
            Ok(n) => {
                *written += n;
                if *written == len {
                    if front.reply {
                        budget.release(len);
                    }
                    write_list.pop_front();
                    *written = 0;
                }
            }
            Err(err) if matches!(err.kind(), ErrorKind::WouldBlock | ErrorKind::Interrupted) => {
                break;
            }
            Err(err) => return Err(err),
        }
    }
    Ok(())
}

fn lock<T>(mutex: &Mutex<T>) -> MutexGuard<'_, T> {
    mutex.lock().unwrap_or_else(PoisonError::into_inner)
}

fn decode(
    request: &ImageRequest,
    args: &image::ImageArgs,
    geometry: CellGeometry,
) -> Option<TermImage> {
    image::decode(request, args, geometry)
        .inspect_err(|err| tracing::debug!(%err, "inline image ignored"))
        .ok()
}

/// [`decode`] on a worker thread. This thread meanwhile takes the messages
/// for the PTY, so keystrokes and resizes aren't held up by a large image.
fn decode_serving(
    input: &mut PtyInput<'_>,
    request: &ImageRequest,
    args: &image::ImageArgs,
    geometry: CellGeometry,
) -> Option<TermImage> {
    std::thread::scope(|scope| {
        let tx = input.tx.clone();
        let worker = scope.spawn(move || {
            let image = decode(request, args, geometry);
            let _ = tx.send(Msg::Decoded);
            image
        });
        while !worker.is_finished() {
            match input.rx.recv_timeout(DECODE_POLL) {
                Ok(msg) => {
                    handle_msg(
                        msg,
                        input.write_list,
                        input.resize,
                        input.shutdown_requested,
                    );
                    // A failure shows again when the loop writes next.
                    let _ = write_pending(input.pty, input.write_list, input.written, input.budget);
                }
                Err(mpsc::RecvTimeoutError::Timeout) => {}
                Err(mpsc::RecvTimeoutError::Disconnected) => std::thread::sleep(DECODE_POLL),
            }
        }
        // A panic in the worker counts as a failed decode.
        worker.join().ok().flatten()
    })
}

/// Run `action` with the output buffered in a synchronized update (DEC
/// 2026) applied first, so images and replies stay in stream order. The
/// update continues afterwards.
fn with_flushed_sync(
    parser: &mut Processor,
    term: &mut Term<Listener>,
    action: impl FnOnce(&mut Term<Listener>),
) {
    if parser.sync_timeout().sync_timeout().is_some() {
        parser.stop_sync(term);
        action(term);
        parser.advance(term, BSU);
    } else {
        action(term);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_are_capped_to_the_locked_read_limit() {
        assert_eq!(read_limit(READ_BUFFER_SIZE), MAX_LOCKED_READ);
        assert_eq!(read_limit(10), 10);
    }

    #[test]
    fn replies_beyond_the_cap_are_refused() {
        let budget = ReplyBudget::default();
        assert!(budget.try_reserve(MAX_PENDING_REPLY_BYTES));
        assert!(!budget.try_reserve(1));
        budget.release(10);
        assert!(budget.try_reserve(10));
        assert_eq!(budget.pending(), MAX_PENDING_REPLY_BYTES);
    }

    #[test]
    fn a_single_oversized_reply_is_refused() {
        let budget = ReplyBudget::default();
        assert!(!budget.try_reserve(MAX_PENDING_REPLY_BYTES + 1));
        assert_eq!(budget.pending(), 0);
    }
}
