name = "Rose Pine Dawn"
foreground = "#575279"
background = "#faf4ed"
cursor = "#cecacd"
selection_foreground = "#575279"
selection_background = "#dfdad9"
normal = ["#f2e9e1", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]
bright = ["#9893a5", "#b4637a", "#286983", "#ea9d34", "#56949f", "#907aa9", "#d7827e", "#575279"]
