#!/bin/sh
# Offer nuntio as x-terminal-emulator (Debian's default-terminal mechanism).
set -e
if [ "$1" = "configure" ]; then
    update-alternatives --install /usr/bin/x-terminal-emulator \
        x-terminal-emulator /usr/bin/nuntio 20
fi
